# Generated by Django 5.0.1 on 2024-03-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=20)),
                ('out_trade_no', models.CharField(max_length=100)),
                ('total_amount', models.FloatField()),
                ('trade_date', models.DateTimeField()),
                ('trade_no', models.CharField(max_length=100, unique=True)),
                ('trade_status', models.IntegerField()),
                ('transaction_no', models.CharField(max_length=100)),
            ],
        ),
    ]
