# Generated by Django 5.0.1 on 2024-04-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebirrpay', '0002_alter_paymentnotification_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentnotification',
            name='paid_by_telebirr',
            field=models.BooleanField(default=True),
        ),
    ]
