# Generated by Django 5.0.1 on 2024-02-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_likes_count_product_product_likes_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_likes_count',
        ),
    ]
