# Generated by Django 5.0.1 on 2024-02-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_product_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_brand',
            field=models.CharField(blank=True, default='Custom', max_length=150),
        ),
    ]
