# Generated by Django 5.0.1 on 2024-02-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
