# Generated by Django 5.0.1 on 2024-02-21 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_product_brand_cartitem_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='selected_pirce',
            new_name='selected_price',
        ),
    ]
