# Generated by Django 5.0.1 on 2024-02-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_rename_selected_pirce_cartitem_selected_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_image_url',
            field=models.URLField(blank=True),
        ),
    ]
