# Generated by Django 5.0.1 on 2024-04-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankpay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paywithbank',
            name='user_bank_account_name',
            field=models.CharField(default='no name', max_length=200),
        ),
    ]
