# Generated by Django 5.0.1 on 2024-04-08 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankpay', '0003_bankname_alter_paywithbank_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankname',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
