# Generated by Django 5.0.1 on 2024-04-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankpay', '0005_paywithbank_paid_by_bank_paywithbank_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paywithbank',
            name='paid_by_bank',
            field=models.BooleanField(default=False),
        ),
    ]
