# Generated by Django 5.0.1 on 2024-04-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankpay', '0006_alter_paywithbank_paid_by_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paywithbank',
            name='paid_by_bank',
            field=models.BooleanField(default=True),
        ),
    ]
