# Generated by Django 5.0.1 on 2024-04-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankpay', '0008_alter_paywithbank_paid_by_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paywithbank',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
