# Generated by Django 5.0.1 on 2024-04-09 04:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankpay', '0009_alter_paywithbank_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankname',
            name='account',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
