# Generated by Django 5.0.1 on 2024-04-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankpay', '0010_bankname_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paywithbank',
            name='ref_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
