# Generated by Django 5.0.1 on 2024-04-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankpay', '0011_alter_paywithbank_ref_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paywithbank',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='paywithbank',
            name='user_bank_account_name',
            field=models.CharField(max_length=200),
        ),
    ]
