# Generated by Django 5.0.1 on 2024-03-22 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rate', models.DecimalField(decimal_places=2, default=0.01, max_digits=5)),
                ('referral_rate', models.DecimalField(decimal_places=2, default=0.01, max_digits=5)),
                ('user_referral_rate', models.DecimalField(decimal_places=2, default=0.01, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PaywithReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('out_trade_no', models.CharField(editable=False, max_length=60)),
                ('transaction_no', models.CharField(blank=True, max_length=100)),
                ('payment_status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
