# Generated by Django 5.0.1 on 2024-02-11 14:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('order_phone', models.CharField(max_length=13)),
                ('order_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('order_address', models.CharField(max_length=100)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_total_prices', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
    ]
