# Generated by Django 5.0.1 on 2024-02-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_email_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='received', max_length=20),
        ),
    ]
