# Generated by Django 5.0.1 on 2024-02-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('in_progress', 'In Progress'), ('complete', 'Completed')], default='received', max_length=20),
        ),
    ]
