# Generated by Django 5.0.1 on 2024-03-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_order_phone_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='outTradeNo',
            field=models.CharField(default=1, editable=False, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_no',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
