# Generated by Django 5.0.1 on 2024-03-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='referral_code',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
