# Generated by Django 5.0.1 on 2024-03-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_key',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
