# Generated by Django 5.0.1 on 2024-04-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_order_order_email_order_order_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_by_points',
            field=models.BooleanField(default=False),
        ),
    ]
