# Generated by Django 5.0.1 on 2024-04-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orderitem_delivered_orderitem_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_by_bank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_by_telebirr',
            field=models.BooleanField(default=False),
        ),
    ]
