# Generated by Django 5.0.1 on 2024-04-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_paid_by_bank_order_paid_by_telebirr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_phone',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
