# Generated by Django 5.0.1 on 2024-04-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_bank_ref_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
